apiVersion: apps/v1
kind: Deployment
metadata:
  name: rustfs
  namespace: rustfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rustfs
  template:
    metadata:
      labels:
        app: rustfs
    spec:
      containers:
        - name: rustfs
          image: rustfs/rustfs:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: s3
              containerPort: 9000
            - name: console
              containerPort: 9001
          env:
            # - name: RUSTFS_ADDRESS
            #   value: "0.0.0.0:9000"
            - name: RUSTFS_DATA_DIR
              value: "/data"
            # - name: RUSTFS_CONSOLE_ADDRESS
            #   value: "0.0.0.0:9001"
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rustfs-data
